openapi: 3.0.0        
components:                   
  schemas:        
    AnonymousType0:                      
      type: object
      properties:                            
        A:   
          type: string                                                                            
      required:
      - A
    AnonymousType1: 
      type: object
      properties:
        B:
          type: string        
      required:
      - B
info:           
  title: anonymous-type.yaml             
  version: 0.0.0   
paths:                                                                                            
  /test:        
    post:                                                                                         
      requestBody:       
        content:
          application/json:     
            schema:  
              $ref: '#/components/schemas/AnonymousType0'                                         
      responses:                             
        "200":                      
          description: ""                                                                         
          content:                                                                                
            application/json:
              schema:
                $ref: '#/components/schemas/AnonymousType1'
        default:
          description: ""

