openapi: 3.0.0
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
info:
  title: route-params.yaml
  version: 0.0.0
paths:
  /organisation/{orgId:\d+}/user/{userId}:
    get:
      parameters:
        - in: path
          name: orgId
          required: true
          schema:
            type: string
            pattern: \d+
        - in: path
          description: User ID
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: ""
