openapi: 3.0.0
components:
  schemas:
    WithMaps:
      properties:
        amounts:
          additionalProperties:
            type: integer
          nullable: true
          type: object
      required:
      - amounts
      type: object
info:
  title: with-maps.yaml
  version: 0.0.0
paths:
  /get:
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WithMaps'
        default:
          description: ""

